# Generated by Django 4.1.5 on 2023-01-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data aktualizacji')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('size', models.DecimalField(decimal_places=2, error_messages={'unique': 'Taka średnica już istnieje w bazie danych.'}, max_digits=6, unique=True, verbose_name='Średnica')),
            ],
            options={
                'verbose_name': 'Średnica',
                'verbose_name_plural': 'Średnice',
                'db_table': 'dimension',
                'ordering': ['size'],
            },
        ),
        migrations.AddIndex(
            model_name='dimensionmodel',
            index=models.Index(fields=['size'], name='dimension_size_idx'),
        ),
        migrations.AddConstraint(
            model_name='dimensionmodel',
            constraint=models.CheckConstraint(check=models.Q(('size__gt', 0)), name='size_gt_0', violation_error_message='Średnica musi być większa od zera.'),
        ),
    ]
