# Generated by Django 4.1.5 on 2023-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_add_heat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data aktualizacji')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Identyfikator')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
                'db_table': 'certificate',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='certificatemodel',
            index=models.Index(fields=['name'], name='certificate_name_idx'),
        ),
    ]
