# Generated by Django 4.1.5 on 2023-01-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_add_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data aktualizacji')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ilość')),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Stan')),
                ('can_modify', models.BooleanField(default=True, verbose_name='Modyfikacja')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplyitem', to='warehouse.certificatemodel', verbose_name='Certyfikat')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplyitem', to='warehouse.dimensionmodel', verbose_name='Średnica')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplyitem', to='warehouse.grademodel', verbose_name='Gatunek')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplyitem', to='warehouse.heatmodel', verbose_name='Wytop')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplyitem', to='warehouse.supplymodel', verbose_name='Przychód')),
            ],
            options={
                'verbose_name': 'Pozycja przychodu',
                'verbose_name_plural': 'Pozycje przychodu',
                'db_table': 'supply_item',
            },
        ),
        migrations.AddIndex(
            model_name='supplyitemmodel',
            index=models.Index(fields=['dimension', 'grade'], name='supplyitem_dimension_grade_idx'),
        ),
    ]
